### ISSUE TITLE
Which scopes required for configuration of authorization token

### ISSUE THREAD

**Issue by natefaerber** [philschatz/atom-pull-requests#15]
Can you document which scopes are required to configure the authorization token?  I would prefer to have the minimum required assigned to this token.

Thanks
-nate

**Comment by derekjobst** [comment]
bump

**Comment by philschatz** [comment]
you don't need to set any scopes; just leave each item unchecked 😄  This should work for both public **and** private repositories. I'll submit a Pull Request updating the `README.md`

**Comment by natefaerber** [comment]
Thanks.  Sorry for the delay in closing.
