### ISSUE TITLE
Keep OAuth key out of config.cson

### ISSUE THREAD

**Issue by bastilian** [philschatz/atom-pull-requests#20]
I just noticed that the OAuth key is saved to atoms `config.scon`, since a number of people are syncing their editor configurations, sometimes even publicly it, presents a hurdle to make sure this key is not pushed to the public.

A suggestion would be to use `keytar` (https://github.com/atom/node-keytar) to store the credentials safely.

**Comment by philschatz** [comment]
Thanks for bringing this up! I finally got some free time over the holidays to work on this 😄 . 

A fix will be in the next version but I still need to clean up #25 a bit. Feel free to comment on the PR!
