### ISSUE TITLE
Deprecated selector in `pull-requests/styles/pull-requests.atom-text-editor.less`

### ISSUE THREAD

**Issue by molovo** [philschatz/atom-pull-requests#21]
In `pull-requests/styles/pull-requests.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .linter-gutter.linter-highlight.info:not(.line-number)` => `atom-text-editor.editor .linter-gutter.linter-highlight.syntax--info:not(.line-number)`

* `atom-text-editor::shadow .linter-gutter.linter-highlight.info:not(.line-number)::before` => `atom-text-editor.editor .linter-gutter.linter-highlight.syntax--info:not(.line-number)::before`

* `atom-text-editor::shadow .linter-gutter.linter-highlight.info:not(.line-number)::before` => `atom-text-editor.editor .linter-gutter.linter-highlight.syntax--info:not(.line-number)::before`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by igs-awilliams** [comment]
+1
