### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by dewvas** [philschatz/atom-pull-requests#30]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [pull-requests](https://github.com/philschatz/atom-pull-requests) package 0.1.0

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /Users/Dewvas/.atom/packages/pull-requests/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/pull-requests/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
pull-requests 0.1.0 
```

**Comment by philschatz** [comment]
This should be fixed in `v3.0.0`. Thanks @tevren!
