### ISSUE TITLE
Personal Access Token in Atom config isn't used

### ISSUE THREAD

**Issue by tbehling** [philschatz/atom-pull-requests#33]
Hi there @philschatz, first, this is an awesome idea for an Atom plugin!

I had some trouble getting it to work with a private repo on GitHub.com.  In the README it says to create a Personal Access Token and add it to Atom's `config.cson`.  I did so, but I still got an error from the `pull-requests` plugin that the repo wasn't accessible.  I dug into the code and I found the token in the config appears to not be used; instead the token is being pulled from Keytar.  Does the documentation maybe need to be updated with new steps?

https://github.com/philschatz/atom-pull-requests/blob/b659e9a4f3e674e2b4b4dec9f105a90143b76139/lib/gh-client.coffee#L101

**Comment by philschatz** [comment]
This should be fixed in `v3.0.0`. Thanks @tevren!
