### ISSUE TITLE
Repeated error message, if project is not version controlled with GitHub.

### ISSUE THREAD

**Issue by AshleyWright** [philschatz/atom-pull-requests#5]
I use atom to code on projects hosted on GitHub, BitBucket and private remotes and would love to use this package when on GitHub-hosted projects (BitBucket-hosted as well, if that's possible), but I don't want the annoying error message for other projects.

**Comment by plessbd** [comment]
I would like this as well.  I would think it would just be checking if the origin url has github.com in it...

**Comment by philschatz** [comment]
Thanks for pointing this out! I completely missed this since I use atom only for editing GitHub repos. `0.0.17` should fix this issue. Please let me know if this fixes your issue

**Comment by plessbd** [comment]
this worked for me.

**Comment by philschatz** [comment]
Thanks! Closing this Issue for now.

Also, in `0.0.19` the usernames are now clickable links that go back to the original comment which should make it easier to continue discussing a Pull Request.
